x-frappe-base: &frappe-base
  build:
    context: ..
    dockerfile: .prodcontainer/frappe/Dockerfile
  restart: unless-stopped
  working_dir: /home/frappe/frappe-bench
  env_file: .env
  user: "1000:1000"
  volumes:
    - frappe-sites-data:/home/frappe/frappe-bench/sites
    - frappe-logs-data:/home/frappe/frappe-bench/logs
  networks:
    - bench-network
  depends_on:
    fp-database:
      condition: service_healthy
    fp-redis-cache:
      condition: service_healthy
    fp-redis-queue:
      condition: service_healthy

x-redis: &redis
  image: redis:6.2-alpine
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "redis-cli", "--raw", "incr", "ping_test"]
    start_period: 15s
    interval: 30s
    timeout: 5s
    retries: 5
  networks:
    - bench-network

services:
  fp-web:
    <<: *frappe-base
    command:
      - /home/frappe/frappe-bench/env/bin/gunicorn
      - --chdir=/home/frappe/frappe-bench/sites
      - --bind=0.0.0.0:8000
      - --threads=4
      - --workers=2
      - --worker-class=gthread
      - --worker-tmp-dir=/dev/shm
      - --timeout=120
      - --preload
      - frappe.app:application
    healthcheck:
      test: [
        "CMD",
        "curl",
        "--fail",
        "-H",
        "X-Frappe-Site-Name: ${DFP_DOMAIN_NAME}",
        "http://0.0.0.0:8000/api/method/frappe.ping"
      ]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 5

  fp-websocket:
    <<: *frappe-base
    command:
      - /bin/sh
      - -c
      - sleep 20 && node /home/frappe/frappe-bench/apps/frappe/socketio.js
    healthcheck:
      test: [
        "CMD",
        "curl",
        "--fail",
        "http://localhost:9000/socket.io/?EIO=4&transport=polling"
        ]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 5

  fp-worker-short:
    <<: *frappe-base
    command:
      - bench
      - worker
      - --queue
      - short,default

  fp-worker-long:
    <<: *frappe-base
    command:
      - bench
      - worker
      - --queue
      - long,default,short

  fp-schedule:
    <<: *frappe-base
    command:
      - bench
      - schedule

  fp-clear-cache:
    <<: *frappe-base
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    command:
      - redis-cli
      - -h
      - fp-redis-cache
      - DEL
      - assets_json

  fp-redis-cache:
    <<: *redis

  fp-redis-queue:
    <<: *redis
    volumes:
      - redis-queue-data:/data

  fp-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      additional_contexts:
        frappe-image: service:fp-web
    restart: unless-stopped
    env_file: .env
    volumes:
      - frappe-sites-data:/home/frappe/frappe-bench/sites
    networks:
      bench-network:
        aliases:
          - ${DFP_DOMAIN_NAME}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/nginx-healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 5

  fp-database:
    image: mariadb:11.8
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MARIADB_ROOT_PASSWORD: ${DFP_DB_ROOT_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - bench-network

volumes:
  mariadb-data:
  redis-queue-data:
  frappe-sites-data:
  frappe-logs-data:

networks:
  bench-network:
